title: "Health Dashboard"
output:
  format: html
  filename: "docs/health-dashboard.html"
setup: |
  const repos = 'repo:Azure/login repo:Microsoft/variable-substitution repo:Azure/appservice-settings repo:Azure/webapps-deploy repo:Azure/aci-deploy repo:build-vm-image repo:Azure/functions-action repo:Azure/functions-container-action repo:Azure/mysql repo:Azure/postgresql repo:Azure/powershell repo:Azure/sql-action repo:Azure/policy-compliance-scan repo:Azure/k8s-create-secret repo:Azure/k8s-lint repo:Azure/k8s-deploy repo:Azure/manage-azure-policy repo:Azure/setup-kubectl repo:Azure/k8s-bake repo:Azure/aks-set-context repo:Azure/k8s-set-context repo:Azure/setup-helm repo:Azure/container-scan repo:Azure/docker-login repo:Azure/publish-security-assessments repo:Azure/static-web-apps-deploy repo:Azure/get-keyvault-secrets repo:Azure/AppConfiguration-Sync repo:Azure/arm-deploy repo:Azure/cli'
  userdata.count = async function(itemType,label) {
    return '2'
  }

  userdata.url = async function(itemType,label) {
    return ''
  } 
  userdata.getTimeStamp = async function(itemType,label) {
    var today = new Date();
    var utcTime = today.getTime() + (today.getTimezoneOffset() * 60000);
    var istTime = new Date(utcTime + (3600000*5.5));
    return istTime.toLocaleString();
  }


  - title: "Details"
    widgets:
      - type: "string"
        value: "Issues detailed information"
        url: "issue.html"
      - type: "string"
        value: "PR detailed information"
        url: "pr.html"
      - type: "string"
        value: "Last updated : {{ userdata.getTimeStamp() }} IST"
        color: black
        
