name: keyvault-secrets

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
#     - uses: Azure/login@v1
#       with:
#         creds: ${{ secrets.AZURE_CREDENTIALS }} 
#     - uses: Azure/get-keyvault-secrets@v1
#       with:
#         keyvault: "kptestvault101"
#         secrets: 'kp-test-secret'
#       id: myGetSecretAction
    - uses: Azure/docker-login@v1
      with:
        login-server: kptestregistry.azurecr.io
        username: kptestregistry
        password: abc
    - run: |
        docker build . -t kptestregistry.azurecr.io/k8sdemo:${{ github.sha }}
        docker push kptestregistry.azurecr.io/k8sdemo:${{ github.sha }}
#     - run: |
#         cd go-sample
#         docker build . -t my.azurecr.io/myimage:${{ github.sha }}
#         docker push my.azurecr.io/myimage:${{ github.sha }}
#         cd ..
 
