name: keyvault-secrets

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
#     - uses: Azure/get-keyvault-secrets@v1
    - uses: bcatania18/get-keyvault-secrets@fix_posix_envvars
      with:
        keyvault: "kptestvault101"
        secrets: 'kp-test-secret-key'
      id: myGetSecretAction
    - uses: Azure/login@v1
      with:
  #          creds: $kp-test-secret-key
            creds: ${{ steps.myGetSecretAction.outputs.kp-test-secret-key }} 

#     - uses: Azure/docker-login@v1
#       with:
#         login-server: kptestregistry.azurecrqwerty.io
#         username: kptestregistry
#         password: abc
#     - run: |
#         echo ${{ steps.myGetSecretAction.outputs.kp-test-secret }}.ToCharArray()
 
