# This is a basic workflow to help you get started with Actions

name: variable-substitution-test

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: microsoft/variable-substitution@v1 
      with:
        files: 'jsonTest.json'
      env:
        name: "newName"
